---
title: "Project5"
author: "Ann Liu-Ferrara"
date: "July 5, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Implementing a Recommender System on Spark

Using sparklyr package in R to implement the Recommender System


```{r cars}
if (!require('sparklyr')) install.packages('sparklyr')
if (!require('dplyr')) install.packages('dplyr')
if (!require('reshape2')) install.packages('reshape2')
if (!require('recommenderlab')) install.packages('recommenderlab')
if (!require('ggplot2')) install.packages('ggplot2')
if (!require('XML')) install.packages('XML')

sparklyr::spark_install(version = "1.6.2")
java_path <- normalizePath('C:/Program Files/Java/jre1.8.0_131')
Sys.setenv(JAVA_HOME=java_path)

sc <- spark_connect(master = "local")

# copy mtcars into spark
mtcars_tbl <- copy_to(sc, mtcars)

# transform our data set, and then partition into 'training', 'test'
partitions <- mtcars_tbl %>%
  filter(hp >= 100) %>%
  mutate(cyl8 = cyl == 8) %>%
  sdf_partition(training = 0.5, test = 0.5, seed = 1099)

# fit a linear model to the training dataset
fit <- partitions$training %>%
  ml_linear_regression(response = "mpg", features = c("wt", "cyl"))


spark_disconnect(sc)
```

